services:
  app:
    build:
      args:
        user: ${DOCKER_COMPOSE_USER}
        uid: ${DOCKER_COMPOSE_UID}
      context: .
      dockerfile: .docker/Dockerfile
    image: node_app
    container_name: node_app
    restart: unless-stopped
    tty: true
    ports:
      - "3060:80"
    environment:
      NODE_ENV: development
    networks:
      - app
networks:
  app:
    driver: bridge